### ISSUE TITLE
Organize domains using folders

### ISSUE THREAD

**Issue by dtdannen** [mclumd/MIDCA#3]
Domains could be organized more clearly. When creating a domain, generally the following files are needed:

methods.py ;; used for planner, stored under modules\_plan
operators.py ;; used for planner, stored under modules\_plan
<domain-name>.sim ;; used for midca simulator to specify action model, stored under worldsim\domains
defstate-<domain-name>.sim ;; used for the starting state when MIDCA simulator starts up, stored under worldsim\states

However, it would be ideal to simply have a domains folder where each domain (e.g. blocksworld) has its own folder that contains all the files (used either by the planner or world simulator).

**Comment by mpaisner** [comment]
Seconded. Also, really cool to see you're still working on this stuff!

-Matt
